export declare const PARENT: unique symbol;
export declare const FOR_VALUE: string;
export declare const FOR_INDEX: string;
export declare const FOR_WATCHER_KEY: string;
export declare const PARENT_FRAME: unique symbol;
export declare const ENDING_ANIMATE: unique symbol;
export declare const SUSPENSE: unique symbol;
export declare const CHILDREN: unique symbol;
export declare const ANIMATE_PARAMS_PROPS: ["height", "width", "opacity", "backgroundColor", "rotate", "scale"];
export declare const ANIMATE_PARAMS: ["height", "width", "opacity", "backgroundColor", "rotate", "scale", "translate"];
export declare const ANIMATE_PROPS: readonly ["height", "width", "opacity", "backgroundColor", "rotate", "scale", "scaleX", "scaleY", "translateX", "translateY", "rotateX", "rotateY"];
