import { AbsoluteLayout, ActionBar, ActionItem, ActivityIndicator, Button, DatePicker, DockLayout, FlexboxLayout, FormattedString, Frame, GridLayout, HtmlView, Image, Label, ListPicker, ListView, NavigationButton, Placeholder, Progress, RootLayout, ScrollView, SearchBar, SegmentedBar, SegmentedBarItem, Slider, Span, StackLayout, Switch, TabView, TabViewItem, TextField, TextView, TimePicker, WebView, WrapLayout } from '@nativescript/core';
import { Fragment, InPage } from './utils/views';
export declare const JSX_ELEMENTS: {
    label: typeof Label;
    'root-layout': typeof RootLayout;
    'flexbox-layout': typeof FlexboxLayout;
    'formatted-string': typeof FormattedString;
    switch: typeof Switch;
    button: typeof Button;
    span: typeof Span;
    'stack-layout': typeof StackLayout;
    'grid-layout': typeof GridLayout;
    'wrap-layout': typeof WrapLayout;
    'dock-layout': typeof DockLayout;
    'absolute-layout': typeof AbsoluteLayout;
    frame: typeof Frame;
    page: typeof InPage;
    'action-bar': typeof ActionBar;
    'action-item': typeof ActionItem;
    fragment: typeof Fragment;
    image: typeof Image;
    'navigation-button': typeof NavigationButton;
    'activity-indicator': typeof ActivityIndicator;
    'date-picker': typeof DatePicker;
    'html-view': typeof HtmlView;
    'list-picker': typeof ListPicker;
    'list-view': typeof ListView;
    placeholder: typeof Placeholder;
    progress: typeof Progress;
    'scroll-view': typeof ScrollView;
    'search-bar': typeof SearchBar;
    'segmented-bar': typeof SegmentedBar;
    'segmented-bar-item': typeof SegmentedBarItem;
    slider: typeof Slider;
    'tab-view': typeof TabView;
    'tab-view-item': typeof TabViewItem;
    'text-field': typeof TextField;
    'text-view': typeof TextView;
    'time-picker': typeof TimePicker;
    'web-view': typeof WebView;
};
